config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  get 'projects/index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/projects', to: 'projects#index'
  get '/contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/index.html.erb
<!-- Contact#index
#Find me in app/views/contact/index.html.erb -->
<div class="container mt-5">
<form class="row g-3">
  <div class="col-md-4">
    <label for="validationServer01" class="form-label">Nombre</label>
    <input type="text" class="form-control" id="validationServer01" required>
    <div class="valid-feedback">
      Por favor, coloque su nombre.
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationServer01" class="form-label">Apellido</label>
    <input type="text" class="form-control" id="inputGroupPrepend3" required>
    <div class="valid-feedback">
      Por favor, coloque su apellido.
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationServerUsername" class="form-label">Nombre de usuario</label>
    <div class="input-group has-validation">
      <span class="input-group-text" id="inputGroupPrepend3">@</span>
      <input type="text" class="form-control" id="validationServerUsername" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" required>
      <div id="validationServerUsernameFeedback" class="invalid-feedback">
        Por favor, elija un nombre de usuario.
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <label for="validationServer03" class="form-label">Ciudad</label>
    <input type="text" class="form-control" id="validationServer03" aria-describedby="validationServer03Feedback" required>
    <div id="validationServer03Feedback" class="invalid-feedback">
      Proporcione una ciudad válida.
    </div>
  </div>
<div class="col-md-3">
  <label for="validationServer04" class="form-label">Región</label>
  	<select class="form-select" id="validationServer04" aria-describedby="validationServer04Feedback" required>
		<option selected disabled value="">Elegir...</option>
		<option value="1">Arica y Parinacota</option>
		<option value="2">Tarapacá</option>
		<option value="3">Antofagasta</option>
		<option value="4">Atacama</option>
		<option value="5">Coquimbo</option>
		<option value="6">Valparaíso</option>
		<option value="7">Metropolitana de Santiago</option>
		<option value="8">Libertador General Bernardo O'Higgins</option>
		<option value="9">Maule</option>
		<option value="10">Ñuble</option>
		<option value="11">Biobío</option>
		<option value="12">Araucanía</option>
		<option value="13">Los Ríos</option>
		<option value="14">Los Lagos</option>
		<option value="15">Aysén del General Carlos Ibáñez del Campo</option>
		<option value="16">Magallanes y de la Antártica Chilena</option>
  	</select>
  <div id="validationServer04Feedback" class="invalid-feedback">
    Seleccione una región válida.
  </div>
  </div>
  <div class="col-md-3">
    <label for="validationServer05" class="form-label">Código Postal</label>
    <input type="text" class="form-control" id="validationServer05" aria-describedby="validationServer05Feedback" required>
    <div id="validationServer05Feedback" class="invalid-feedback">
      Proporcione un código postal válido.
    </div>
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck3" aria-describedby="invalidCheck3Feedback" required>
      <label class="form-check-label" for="invalidCheck3">
        Acepto los términos y condiciones
      </label>
      <div id="invalidCheck3Feedback" class="invalid-feedback">
        Acepto los términos y condiciones
      </div>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Enviar</button>
  </div>
</form>
</div>

app/views/home/index.html.erb
<!-- #Home#index
#Find me in app/views/home/index.html.erb -->
<div class="container mt-5">
  <h1>Bienvenidos a mi portafolio</h1>
  	<p>¡Hola queridos cibernautas! Los invito a explorar mi sitio web y descubrir mi trabajo.</p>
  	<p>Si estás interesado en mis proyectos, visita la página de <%= link_to "Proyectos", projects_path %>.</p>
  	<p>Si deseas ponerte en contacto conmigo, puedes ir a la página de <%= link_to "Contacto", contact_path %>.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mi Portafolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'style', media: 'all' %> 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Proyectos", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contacto", contact_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/index.html.erb
<!-- #Projects#index
#Find me in app/views/projects/index.html.erb -->
<div class="container mt-5">
	<div class="row">
	  <div class="col-md-4">
	    <div class="card">
		 <%= image_tag('image1.png', class: 'card-img-top', alt: 'Proyecto 1') %>
	      <div class="card-body">
	        <h5 class="card-title">Proyecto Suricata</h5>
	        <p class="card-text">Mi primer proyecto realizado en el Bootcamp de Ruby On Rails. Suspendisse potenti. Morbi auctor pulvinar congue. Phasellus fermentum purus et condimentum semper. Sed maximus arcu congue quam interdum mollis.</p>
	        <a href="#" class="btn btn-primary custom-button">Ver más</a>
	      </div>
	    </div>
	  </div>

	  <div class="col-md-4">
	    <div class="card">
		 <%= image_tag('image2.png', class: 'card-img-top', alt: 'Proyecto 2') %>
	      <div class="card-body">
	        <h5 class="card-title">Proyecto Olivia Ros</h5>
	        <p class="card-text">Mi segundo proyecto realizado en el Bootcamp de Ruby On Rails. Mauris malesuada elit purus, sed ultrices massa porta ac. Aliquam aliquam suscipit urna, non semper libero sollicitudin ut. Curabitur erat mi, vestibulum at.</p>
	        <a href="#" class="btn btn-primary custom-button">Ver más</a>
	      </div>
	    </div>
	  </div>

	  <div class="col-md-4">
	    <div class="card">
		 <%= image_tag('image3.png', class: 'card-img-top', alt: 'Proyecto 3') %>
	      <div class="card-body">
	        <h5 class="card-title">Proyecto Ricomida</h5>
	        <p class="card-text">Mi tercer proyecto realizado en el Bootcamp de Ruby On Rails. Fusce quis ultrices mi. Proin convallis neque consectetur turpis varius varius. Nunc gravida tincidunt molestie. Suspendisse lobortis suscipit nibh in.</p>
	        <a href="#" class="btn btn-primary custom-button">Ver más</a>
	      </div>
	    </div>
	  </div>
	</div>
</div>